### ISSUE TITLE
git.Clone does not support caching

### ISSUE THREAD

**Issue by kriko** [kestra-io/plugin-git#50]
### Expected Behavior

Using WorkingDirectory parent task with cache enabled, git.Clone should use the cache and only clone changes/updates from the repository - thus making cloning/pulling more efficient.

### Actual Behaviour

Error in execution, logs:
```
Start cloning from 'https://gitlab...'
Destination path "..." already exists and is not an empty directory
org.eclipse.jgit.api.errors.JGitInternalException: Destination path "..." already exists and is not an empty directory
	at org.eclipse.jgit.api.CloneCommand.verifyDirectories(CloneCommand.java:255)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:178)
	at io.kestra.plugin.git.Clone.run(Clone.java:135)
	at io.kestra.plugin.git.Clone.run(Clone.java:19)
	at io.kestra.core.runners.Worker$WorkerThread.lambda$run$1(Worker.java:707)
	at net.jodah.failsafe.Functions.lambda$toSupplier$10(Functions.java:262)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:48)
	at net.jodah.failsafe.TimeoutExecutor.lambda$supply$1(TimeoutExecutor.java:93)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
	at net.jodah.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:212)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:707)
```

### Steps To Reproduce

Used the flow below.

### Environment Information

- Kestra Version: 0.15.0-SNAPSHOT
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
tasks:
  - id: ci-cd-flows
    type: io.kestra.core.tasks.flows.WorkingDirectory
    cache:
      patterns:
        - "**"
      ttl: PT15M
    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: "https://gitlab..."
        branch: "master"
        username: "kestra"
        password: "{{ secret('GITLAB_TOKEN') }}"
        depth: 1
        timeout: PT1M
```

**Comment by anna-geller** [comment]
it's planned to be addressed in https://github.com/kestra-io/plugin-git/issues/56 by adding a `cache` property directly in the task (without WorkingDirectory)
